---
workspace: /root

ruby_install_bundler: true

# A list of Ruby gems to install.
ruby_install_gems:
  - name: bundler
  - name: nokogiri
    version: '1.8.2'
  - name: pg
    version: '0.21.0'
  - name: execjs
  - name: therubyracer

# The user account under which Ruby gems will be installed.
ruby_install_gems_user: "{{ app_user }}"

ruby_install_from_source: true
ruby_download_url: http://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.4.tar.gz
ruby_version: 2.6.4
ruby_source_configure_command: ./configure --enable-shared

ruby_rubygems_package_name: rubygems
