---
- name: "Copy slurm_service app code"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/{{ local_app_code }}"
    dest: "{{ app_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Copy nginx.conf
  ansible.builtin.copy:
  copy:
     src: "{{ playbook_dir }}"/files/nginx.conf
     dest: "{{ local_app_code }}"/config/nginx.conf

- name: Create directory unix
  file:
    path: /var/run/puma
    owner: "{{ app_user }}"
    state: directory
    mode: '0755'

- name: Install requirements for an app
  ansible.builtin.shell: |
     /usr/local/bin/bundle config build.nokogiri --use-system-libraries
     /usr/local/bin/bundle install --clean --no-cache --without development
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_method: sudo
  become_user: "{{ app_user }}"
  ignore_errors: true
