---
#- name: "Copy slurm_service app code"
#  ansible.builtin.copy:
#    src: "{{ playbook_dir }}/{{ local_app_code }}"
#    dest: "{{ app_dir }}"
#    owner: "{{ app_user }}"
#    group: "{{ app_user }}"
#    mode: "0644"

- name: Copy nginx.conf
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/nginx.conf"
    dest: "{{ app_dir }}/config/nginx.conf"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Create directory unix
  file:
    path: /var/run/puma
    owner: "{{ app_user }}"
    state: directory
    mode: '0755'

- name: Install requirements for an app
  ansible.builtin.shell: |
     /usr/local/bin/bundle config build.nokogiri --use-system-libraries
     /usr/local/bin/bundle install --no-cache --without development
     /usr/local/bin/bundle exec rake assets:precompile RAILS_ENV="{{ rails_env }}" SECRET_KEY_BASE="{{ app_secret }}"
  args:
    chdir: "{{ app_dir }}"
  become: yes
  become_method: sudo
  become_user: "{{ app_user }}"
  ignore_errors: true
#     /usr/local/bin/bundle install --clean --no-cache --without development
