version: "3"

services:
  db:
    image: postgres:13-alpine
    hostname: db
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=2sDM1az
      - POSTGRES_DB=app
    volumes:
      - /var/app/db:/var/lib/postgresql/data
    networks:
     static-network:
      ipv4_address: 10.33.33.100

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - app-socket:/var/run/puma
      - ./xpaste_practicum/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
     static-network:
      ipv4_address: 10.33.33.101

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SECRET_KEY_BASE=$SECRET_KEY_BASE
        - RAILS_ENV=$RAILS_ENV
        - RAILS_LOG_TO_STOUT=$RAILS_LOG_TO_STDOUT
        - DB_HOST=$DB_HOST
        - DB_PORT=$DB_PORT
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
    depends_on:
      - db
    environment:
      - SECRET_KEY_BASE=34mvds2
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=1
      - DB_HOST=10.33.33.100
      - DB_PORT=5432
      - DB_NAME=app
      - DB_USER=app
      - DB_PASSWORD=2sDM1az
    volumes:
#      - .:/app
      - app-socket:/var/run/puma
    networks:
     static-network:
      ipv4_address: 10.33.33.102

volumes:
  app-socket:

networks:
    static-network:
        ipam:
            config: [{subnet: 10.33.33.0/24, ip_range: 10.33.33.192/28}]
