---
__ruby_packages:
  - ruby
  - ruby-devel
  - "{{ ruby_rubygems_package_name }}"
  - '@development tools'
  - libxml2-devel
  - libxslt-devel
  - epel-release
  - nodejs
__ruby_build_packages:
  - '@development tools'
  - zlib-devel
  - openssl-static
